### ISSUE TITLE
Docs: using wp.dev as an example domain

### ISSUE THREAD

**Issue by luc122c** [wp-cli/core-command#112]
In the [documentation ](https://developer.wordpress.org/cli/commands/core/install/)for `wp core install` you use `wp.dev` as an example domain. 
> then you’ll need to run `wp option update siteurl http://wp.dev/wp `

However, now that the `.dev` TLD actually exists and `wp.dev` is not registered, perhaps this should be changed to example.com or any of the other [example domains](https://tools.ietf.org/html/rfc2606#section-3). 

As a side note, http://wp.dev/wp is invalid as the `.dev` TLD is on the HSTS Preload list.

**Comment by schlessera** [comment]
Yes, using example.com is preferable. Do you care for providing a PR for this change?

**Comment by luc122c** [comment]
@schlessera I have created a pull request which builds on the change that @wojsmol made.
