### ISSUE TITLE
"Some of your translations need updating" message and HTML output on the CLI

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/core-command#124]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When performing a core update, the "Some of your translations need updating" message and page HTML and JavaScript from WordPress core gets output to the CLI, causing a lot of visual noise. See below for the full output.

**Describe how other contributors can replicate this bug**

1. Switch to a language other than the default English (US).
2. Perform a core update with `wp core update`.
3. Observe that the "Some of your translations need updating" message appears in the output, along with a load of HTML that core uses on its Updates page.

**Describe what you would expect as the correct outcome**

This message should be customised for the CLI, with HTML tags and JavaScript removed.

**Let us know what environment you are running this on**

```
PHP binary:	/usr/local/Cellar/php/7.3.5/bin/php
PHP version:	7.3.5
php.ini used:	/usr/local/etc/php/7.3/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/sites/wp
WP-CLI packages dir:	/Users/john/.wp-cli/packages/
WP-CLI global config:	/Users/john/.wp-cli/config.yml
WP-CLI project config:	/sites/wp/wp-cli.yml
WP-CLI version:	2.2.0
```

**Provide additional context/Screenshots**

Full output:

```
$ wp core update
Updating to version 5.2 (en_GB)...
Downloading update from https://downloads.wordpress.org/release/en_GB/wordpress-5.2.zip...
Unpacking the update...
<p>Some of your translations need updating. Sit tight for a few more seconds while we update them as well.</p>
<div class="update-messages lp-show-latest"><h2>Updating translations for Query Monitor (en_GB)&#8230;</h2><p>Downloading translation from <span class="code">https://downloads.wordpress.org/translation/plugin/query-monitor/3.3.5/en_GB.zip</span>&#8230;</p>
<p>Unpacking the update&#8230;</p>
<p>Installing the latest version&#8230;</p>
<p>Removing the old version of the translation&#8230;</p>
<p>Translation updated successfully.</p>
</div><div class="update-messages lp-show-latest"><h2>Updating translations for WP Super Cache (en_GB)&#8230;</h2><p>Downloading translation from <span class="code">https://downloads.wordpress.org/translation/plugin/wp-super-cache/1.6.5/en_GB.zip</span>&#8230;</p>
<p>Unpacking the update&#8230;</p>
<p>Installing the latest version&#8230;</p>
<p>Removing the old version of the translation&#8230;</p>
<p>Translation updated successfully.</p>
</div><script type="text/javascript">
					(function( wp ) {
						if ( wp && wp.updates && wp.updates.decrementCount )
							wp.updates.decrementCount( "translation" );
						}
					})( window.wp );
				</script>Success: WordPress updated successfully.
```

**Comment by tomsommer** [comment]
Would be nice to be able to disable updating translations along with core.

**Comment by maximejobin** [comment]
To make it work properly, the [`show_message()`](https://github.com/WordPress/WordPress/blob/3ba44120d0ffa7ac330a1b7e3f8b363ce78f8060/wp-admin/includes/misc.php#L600) function (in WordPress core) will have to be modified as it produces HTML.

An alternative that won't require a core update, but I'm not sure if this would be enough, would be to filter unwanted HTML tags (e.g. `<div>, `<script>`, ...) and keep only `<p>...</p>` tags and apply the equivalent of `strip_tags()`. We would then get an output that would make sense without the HTML. That being said, this looks like a dirty patch.

**Comment by danielbachhuber** [comment]
Closing in favor of this earlier one https://github.com/wp-cli/core-command/issues/191
