### ISSUE TITLE
Add `wp core admin-email` setter command

### ISSUE THREAD

**Issue by mrwweb** [wp-cli/core-command#125]
## Feature Request

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

I frequently encounter the need update the Admin Email setting. Often, getting the new admin email owner to click the confirmation link is a surprisingly onerous task 😭

At present, this can be done with two commands ([kudos](https://stackoverflow.com/a/55451368/597678)), and I believe the confirmation email is triggered even then.

```
$ wp option set admin_email new@example.org
$ wp option set new_admin_email new@example.org
```

This need was alluded to in wp-cli/wp-cli#4713, but the proposed solution involved adjusting the `wp option` command, which I agree didn't make sense.

**Describe the solution you'd like**

I'd like to propose a command like `wp core admin-email {new@example.org}` that will _silently_ update both options.

In some ways it feels like this command makes more sense in `wp config`, but I think the sub commands of `wp core` parallel this new proposed command better, and so it makes sense to put it here.

Based on the previous Issue that raised this use case, I understand the desire not make any precendent-setting changes. However, I think this edge-case is quite unique, and so I'm hopeful that it actually makes a lot of sense to implement!

**Comment by schlessera** [comment]
I don't think that this warrants a separate command, at least not as part of the WP-CLI bundle.

The functionality you need already exists, this change would only turn two working commands into a single working command. In general, adding more code to maintain just to save on some keystrokes is not a good trade-off.

That said, there's nothing keeping you from creating a separate third-party command that integrates the filter that @gitlost referred to in https://github.com/wp-cli/wp-cli/issues/4713 to do this in one line.

Also, I'll accept a PR to the  `wp-cli/extension-command` repository to add the above use case as an example in the help screen for `wp option set`.
