### ISSUE TITLE
`composer phpcs` isn't reporting errors

### ISSUE THREAD

**Issue by nylen** [wp-cli/core-command#137]
Note, I'm reporting this issue here because this is the command I'm developing against. I'm not sure if it applies to other commands also.

Running `composer phpcs` locally reports no errors:

```
~/wp-cli/vendor/wp-cli/core-command $ git status
On branch add/download-from-url
Your branch is up-to-date with 'origin/add/download-from-url'.
nothing to commit, working tree clean
~/wp-cli/vendor/wp-cli/core-command $ git rev-parse HEAD
3740dc565bfe5ae51586a90e674e037b0cece3ca
~/wp-cli/vendor/wp-cli/core-command $ composer phpcs
> run-phpcs-tests


Time: 164ms; Memory: 12MB

~/wp-cli/vendor/wp-cli/core-command $ echo $?
0
```

The phpcs job on Travis reports errors for this same commit ([build log](https://travis-ci.org/wp-cli/core-command/jobs/598172433)):

```
$ composer phpcs

> run-phpcs-tests

...E 4 / 4 (100%)

FILE: src/Core_Command.php

----------------------------------------------------------------------

FOUND 1 ERROR AFFECTING 1 LINE

----------------------------------------------------------------------

 170 | ERROR | [x] Blank line found after control structure

----------------------------------------------------------------------

PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY

----------------------------------------------------------------------

Time: 1.38 secs; Memory: 14MB

Script run-phpcs-tests handling the phpcs event returned with error code 2

The command "composer phpcs" exited with 2.
```

I got here by following the instructions at https://make.wordpress.org/cli/handbook/pull-requests/. I think the issue is that I don't have any PHPCS sniffs installed globally. If that's correct I think there are two ways to fix this:

1. (preferable) Install the required PHPCS rules to the `vendor` directory and run them from there.
2. Document the full PHPCS setup procedure.

**Comment by swissspidy** [comment]
This is probably very outdated by now as there was quite the overhaul of the whole setup in the past few years.

Please reopen if you still run into issues with PHPCS & co.
