### ISSUE TITLE
verify-checksums does not list all added files

### ISSUE THREAD

**Issue by axos88** [wp-cli/core-command#143]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

wp core verify-checksums (and I guess also for plugins) does not report all added files

**Describe how other contributors can replicate this bug**

```
# cd <path/to/wordpress>
# echo x > foo.php
# echo x > foo.txt
# sudo -u www-data wp core verify-checksums 
Warning: File should not exist: wp-salt.php
Success: WordPress installation verifies against checksums.
```

(Does not list foo.php and foo.txt)

**Describe what you would expect as the correct outcome**

The list should contain foo.php and foo.txt as "files should not exist"

**Let us know what environment you are running this on**

```
OS:	Linux webfe.akosv.com 3.13.0-147-generic #196-Ubuntu SMP Wed May 2 15:51:34 UTC 2018 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.29
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/wordpress/<snip>
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.1.0
```

**Comment by axos88** [comment]
Same behaviour on 2.4.0:

```
OS:	Linux webfe.akosv.com 3.13.0-147-generic #196-Ubuntu SMP Wed May 2 15:51:34 UTC 2018 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.29
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/wordpress/aszodiallatorvos.hu
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0
```

**Comment by wojsmol** [comment]
@axos88 You run file creation as root but `wp core verify-checksums`as www-data. IMHO wrong result of wp core verify-checksums is caused by permissions issue. Try with files created by www-data.

**Comment by axos88** [comment]
Ha. Nice catch, didn't even think about that. 

But it's not the issue (tested it), nor should it actually cause any issues (if it did, it would be another bug imho), as long as www-data can read those files. And if it can't then it should also say that there are files that cannot be read.

`wp-foo.php` shows up though. WTF?


```
# sudo -u www-data touch foo.php
# sudo -u root touch wp-foo.php
# sudo -u www-data touch wp-foo2.php
# sudo -u www-data wp core verify-checksums

Warning: File should not exist: wp-foo2.php
Warning: File should not exist: wp-foo.php
Success: WordPress installation verifies against checksums.
```

**Comment by schlessera** [comment]
@axos88 The root folder of a WordPress installation can include all sorts of custom files, like config or .env files, analytics verification files, error logs, ...

There's no way to know which files are legit and which ones are not.

That's why WP-CLI has special behavior for the root folder and only checks files that start with `wp-` in that folder. If you write your `foo.txt` into `wp-admin/` or `wp-includes/`, it should be detected.
