### ISSUE TITLE
--skip-content option should download WP without the default themes and plugins

### ISSUE THREAD

**Issue by Awea** [wp-cli/core-command#147]
Hi there,

According to the [documentation](https://developer.wordpress.org/cli/commands/core/download/#options), the command `core download --skip-content` should only exclude plugins and themes, not the `wp-content/languages` directory. By excluding this directory the `--locales=` option is broken.

**Comment by 2crstn** [comment]
Agree, I wondered where the `wp-content` directory went. This should not happen.
