### ISSUE TITLE
Bash example for `wp core is-installed` is not quite right

### ISSUE THREAD

**Issue by lilole** [wp-cli/core-command#152]
The docs at https://developer.wordpress.org/cli/commands/core/is-installed/#examples show an example like this:

```
# Bash script for checking whether WordPress is installed or not
if ! $(wp core is-installed); then
    wp core install
fi
```

But that `if` is not right. It's testing whether the `stdout` of the `wp core is-installed` command is `true` or `false`.

The fix is simple, just remove the command substitution, like:
```
if ! wp core is-installed; then
    wp core install
fi
```

**Comment by ffxluca** [comment]
If only that command **did not** exit with 0 in case of db errors....
```
wp core is-installed; echo $?

<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong>
...
0
```

**Comment by schlessera** [comment]
@ffxluca:
Do you have a custom `WP_CONTENT_DIR . '/db-error.php'` file in your installation?

**Comment by danielbachhuber** [comment]
This was improved with https://github.com/wp-cli/core-command/pull/237
