### ISSUE TITLE
Add a command option for forcing WP install without PHP module dependency checks

### ISSUE THREAD

**Issue by inspiredearth** [wp-cli/core-command#153]
## Feature Request
- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

I am unable to use `wp-cli core install` in an openlitespeed (OLS) server, due to an error that PHP requires mysql and the required module is not installed. 

OLS has its own mysql php package (lsphp74-mysql), that I gather `wp-cli` does not detect. I've also been told the package is called mysqlnd on OLS.

This means I can't use `wp-cli` to install WP in such an environment, because `wp-cli` will abort with the above mentioned error.

I've seen other "issues" where users state they have trouble using wp-cli in a docker environment, in which they have no yet install mysql, or have it installed in another docket container, etc. Eg. https://github.com/wp-cli/wp-cli/issues/1324
This also looks related: https://github.com/wp-cli/ideas/issues/52

**Describe the solution you'd like**

I can see good reason for not removing the `mysql` dependency check entirely, which was the sentiments of the person who closed issue 1324 mentioned above (https://github.com/wp-cli/wp-cli/issues/1324#issuecomment-241722285)

I would like to suggest at least adding a `--force` type option to `wp-cli core install` so the user can choose to bypass checking for PHP related dependencies. At least that way the user who wants to over-ride those checks can do so. Whilst ensuring the typical user won't end up inadvertently installing WP in an environment that is missing key dependencies.

**Comment by AlexKalopsia** [comment]
Hi, is there a solution to this? I tried using `--force` but I still get the mysql error

**Comment by MagnusBrzenk** [comment]
If you use `wp-cli` with the php binary installed by OLS (in my case it's `/usr/local/lsws/lsphp74/bin/php`), then php will be configured for mysql, and you won't get that error. The simplest way to do this is to prepend that php location to your PATH env var:

```
PATH="/usr/local/lsws/lsphp74/bin:$PATH" wp search-replace XXX YYY --dry-run
```

**Comment by swissspidy** [comment]
We have similar checks for other `wp` commands, but as pointed above this is probably best solved through the right server configuration
