### ISSUE TITLE
Inconsistent "minor" flag as compared to wp plugin update

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/core-command#157]
## Bug Report
**Is your bug report directly related to a specific command?**
wp core update

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

wp core update has a "--minor" flag, which actually behaves like the "--patch" flag of "wp plugin update" https://developer.wordpress.org/cli/commands/core/update/

The current behavior of the "wp core update --minor" flag should be moved into a "--patch" flag, and the new "--minor" flag should behave like the "--minor" flag in wp plugin update

**Describe how other contributors can replicate this bug**

only need to check the documentation :-)

**Describe what you would expect as the correct outcome**

e.g.
-- patch: update from 4.3.1->4.3.3
--minor: update from 4.3.1->4.4.2
no flag: update from 4.3.1->5.3.4

**Comment by chesio** [comment]
WordPress core [does not use](https://core.trac.wordpress.org/ticket/43495) semantic versioning, so newest major version is 5.4 and newest minor version is 5.4.1... I guess the flags are named so in order to reflect the core terminology. Plugins on the other hand are free to use semantic versioning.

**Comment by schlessera** [comment]
Yes, indeed. Unfortunately, WordPress Core's versioning does not make any sense at all, so it will be confusing either way. The best we can do right now is just to stick with their terminology.

**Comment by kkmuffme** [comment]
Thanks for the info - even though the numbering doesnt seem to make sense, there is something that does actually make sense underneath & this is why this should be changed in cli too:
patch versions (what now is called "minor") do not contain any breaking changes (depreciations,...) 
-> thus this is a patch (aka how woocommerce and every other sane software handles versioning)

So I suggest to still rename the flag to "--patch" and do what "--minor" does now (aka use the same flag behavior for core update as is used for woocommerce update, as it makes more sense - since it's about breaking changes/deprecations, isn't it? why would someone use the flags if not for that)

**Comment by schlessera** [comment]
@kkmuffme The thing is that such an adjustment to better deal with breaking changes would be ... an extremely drastic breaking change for all hosting providers that rely on the current behavior to automate update behavior.

We cannot just modify the behavior of these flags arbitrarily, it will wreak havoc on a third of the internet, so to speak... ;)
