### ISSUE TITLE
wp core reinstall

### ISSUE THREAD

**Issue by paulschreiber** [wp-cli/core-command#158]
## Feature Request

**Describe your use case and the problem you are facing**

After running `wp core verify-checksums`, and finding something wrong, there is no easy method in the CLI to reinstall core. I ended up using the web UI via `/wp-admin/update-core.php?action=do-core-reinstall`, which is inconvenient to do for dozens of sites.

None of these commands provided the same functionality:
```
wp core install --force
wp core update --force
```

```
wp core download --force
```
seems to have worked (but didn't work in previous attempts)

**Describe the solution you'd like**

```
wp core reinstall
```

**Comment by DanielRuf** [comment]
According to the code this probably downloads the latest version:

`wp core download --force`

Would be good to read the version from the version.php file before doing the download (with an option like `current-version`).

**Comment by schlessera** [comment]
Yes, indeed, `wp core download --force` should be used for that use case. I don't think this warrants a separate command.

I'm closing this issue as not requiring a fix. But feel free to elaborate on the fact that the command did not seem to initially work for you if you think there is a problem with this somewhere.
