### ISSUE TITLE
wp core download unable to find if wordpress installation already exists in case of missing wp-load.php

### ISSUE THREAD

**Issue by anirudhdggl** [wp-cli/core-command#164]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

So if there is an existing, *or corrupt would be the right word*, WordPress installation that has wp-load.php file, but no other files, the CLI script would not detect an old existing WordPress installation and as a result deviate from the normal behavior.

**Describe how other contributors can replicate this bug**

Now this is going to be hilarious. Just run the following commands

```bash
cd ~
mkdir wp-demo
cd wp-demo
touch wp-load.php
wp core download
```

And there you have the warning.

Also try the other way.
```bash
cd ~
mkdir wp-demo
cd wp-demo
wp core download
rm wp-load.php
```

Now make whatever changes you want to make

```bash
wp core download
```

Although the wordpress installation existed, but still despite of giving user any warning all of his files will be overwritten. 

**Describe what you would expect as the correct outcome**

The part of the download function that looks out for existing WordPress installations has a single point of failure, the **wp-load.php**. The expected behavior should be to remove this point of failure

**Let us know what environment you are running this on**

```
OS:     Linux 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.3
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/anirudh/Desktop/wp
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0

```

**Provide a possible solution**

To fix it, you need to remove the single point of failure. Just make sure that the download function checks for any files and folders with wp-* prefix, and if any such file/folder exist, output a warning to the user and ask for his confirmation before proceeding.

This would ensure that neither we overwrite his file, nor do we prevent him from installing wordpress, just because he has an empty wp-load.php

**Provide additional context/Screenshots**

![wp bug](https://user-images.githubusercontent.com/19634115/87860248-85115780-c959-11ea-8a1d-8d439caf9773.jpg)

**Note**: If this is not intentional and you want to fix it, I would like to be assigned to fix this issue for you.

**Comment by danielbachhuber** [comment]
Fixing this should be a matter of applying https://gist.github.com/danielbachhuber/9b137817e119321f03b9d09df855b3fb and writing some tests for it

**Comment by hbhalodia** [comment]
Hi @danielbachhuber, I would like to contribute to this. Here is my input,

- Instead, checking some files like `wp-mail, `wp-cron` etc. Then we can scan the entire directory and can take help of regex to identify the `wp-` prefix files with `.php` as an extension. 
- Then we can check for if any of the files are present, we can have the user confirmation within cli for `y/n` (if --force is not passed) then proceed further to either download the core files again or not.

Here is what I am talking about, at file - https://github.com/wp-cli/core-command/blob/e3212a3e18fe4affabc54c76cc6a59f3d8059d24/src/Core_Command.php#L140
```php
// Before code...

// To check the entire directory for WordPress files.
$wordpress_present = preg_grep( '~^wp-.*\.php$~', scandir( $download_dir ) );

// Check if files are present and --force is not given as param.
// Confirm user to download the WordPress core.
if ( is_array( $wordpress_present ) && ! empty( $wordpress_present ) && ! Utils\get_flag_value( $assoc_args, 'force' ) ) {
	WP_CLI::confirm( 'WordPress files seem to already be present here. Would you like to continue?' );
}

// After code....
``` 

Let me know if this sounds good or some other approach we can think of, I am happy to provide the patch for any of the approach. Thanks.

**Comment by danielbachhuber** [comment]
Hey @hbhalodia,

I don't think we need the more complex solution at this time. We can simply apply https://gist.github.com/danielbachhuber/9b137817e119321f03b9d09df855b3fb and add some tests.

**Comment by hbhalodia** [comment]
Thanks @danielbachhuber, Would try to add this and raise the PR for the same.

**Comment by hbhalodia** [comment]
Hi @danielbachhuber, have raised the PR for the same. I have added some comment on PR description about test. 
Can you please take a look if we needed an extra test here, as test is already generalized?
