### ISSUE TITLE
requested locale not found, latest version

### ISSUE THREAD

**Issue by thedavidthomas** [wp-cli/core-command#168]
This bug report relates to the `wp core download` command

Using WP-CLI 2.4.0, the command `wp core download --locale="en_AU" --version="latest"` results in a “Error: The requested locale (en_AU) was not found.”

Specifying a version number 5.5 works as expected.
`wp core download --locale="en_AU" --version="5.5"`

Digging deeper it appears this is because 5.5.1 is not available for the en_AU locale

Is it possible for this command to download the latest available version or add a new `latest-available` flag?

**Comment by wojsmol** [comment]
To workaround this issue I'm using
```bash
wp core install ....
wp core language install pl_PL --activate
```
in my deploy script

**Comment by Rvervuurt** [comment]
Same as OP, and it has been like this for years. It works with `nl_NL`, but not with `da_DK`. The "workaround" by @wojsmol works, but is an unnecessary step, since apparently the language pack exists when doing `wp language core install da_DK` (`core language` also works, I've found out).
