### ISSUE TITLE
wp core config refers to outdated Codex URL

### ISSUE THREAD

**Issue by pjohanneson** [wp-cli/core-command#173]
## Bug Report

- [ X ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ X ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

`wp core config --prompt` creates a `wp-config.php` file with a link to an outdated Codex URL.

**Describe how other contributors can replicate this bug**

- Run `wp core download`
- Run `wp core config --prompt`
- After entering info for the prompts, edit `wp-config.php`. The following appears on line 16:

  > ` @link https://codex.wordpress.org/Editing_wp-config.php`

**Describe what you would expect as the correct outcome**

This line should be replaced with `@link https://wordpress.org/support/article/editing-wp-config-php/`, which is present in `wp-config-sample.php`.

**Let us know what environment you are running this on**

```
% wp cli info
OS:	Linux 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.4
PHP version:	7.4.7
php.ini used:	/etc/php/7.4/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/tmp
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0```

**Comment by janw-me** [comment]
A candidate for _good-first-issue_ ?

**Comment by wojsmol** [comment]
No since this is already fixed

**Comment by schlessera** [comment]
This was fixed via https://github.com/wp-cli/config-command/pull/139
