### ISSUE TITLE
wp core multisite-install --url creates a multisite at the wrong domain.

### ISSUE THREAD

**Issue by n-goncalves** [wp-cli/core-command#177]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I am trying to use wp-cli to install a wordpress multisite. My issue is that when I run the `wp core multisite-install` command and give it my URL using the --url parameter, it adds a extra `data` after my domain which causes the network to be created at the wrong URL. For instance if my domain is `blogs.localhost`, I end up with `blogs.localhostdata` in wp-config.php and in the database.
If that helps the issue also occurs when using `wp core install`. 

**Describe how other contributors can replicate this bug**

Here's the script I used to try to create a wordpress multisite network from scratch, assuming the correct database values and that the database 'wordpress' exists. I used --force wherever possible in order to make it easier to replay the script as needed.

```bash
    php /wp-cli.phar core download --locale=fr_FR --force

    php /wp-cli.phar config create \
        --dbhost="db" \
        --dbname="wordpress" \
        --dbuser="user" \
        --dbpass="password \
        --dbcharset="utf8mb4" \
        --locale="fr_FR" \
        --force

    php /wp-cli.phar db reset --yes

    php /wp-cli.phar core multisite-install \
        --subdomains --skip-email \
        --url="blogs.localhost" \
        --title="Plateforme de blogs " \
        --admin_user="adminuser" \
        --admin_email="adminuser@fake.localhost"
```

After running this, here is the multisite part of wp-config.php
```php
define( 'WP_ALLOW_MULTISITE', true );
define( 'MULTISITE', true );
define( 'SUBDOMAIN_INSTALL', false );
$base = '/';
define( 'DOMAIN_CURRENT_SITE', 'blogs.localhostdata' );
define( 'PATH_CURRENT_SITE', '/' );
define( 'SITE_ID_CURRENT_SITE', 1 );
define( 'BLOG_ID_CURRENT_SITE', 1 );
```

and in my database 
```mysql
mysql> SELECT * FROM wp_site;
+----+---------------------+------+
| id | domain              | path |
+----+---------------------+------+
|  1 | blogs.localhostdata | /    |
+----+---------------------+------+
1 row in set (0.00 sec)

mysql> SELECT blog_id, site_id, domain FROM wp_blogs;
+---------+---------+---------------------+
| blog_id | site_id | domain              |
+---------+---------+---------------------+
|       1 |       1 | blogs.localhostdata |
+---------+---------+---------------------+
1 row in set (0.00 sec)

```

**Describe what you would expect as the correct outcome**

wp core multisite-install uses the value provided using the --url parameter as the domain without adding anything. 

**Let us know what environment you are running this on**

Inside a docker container using alpine as a base

```
wordpress_1     | OS:	Linux 5.10.7-3-MANJARO #1 SMP PREEMPT Fri Jan 15 21:11:34 UTC 2021 x86_64
wordpress_1     | Shell:	
wordpress_1     | PHP binary:	/usr/bin/php7
wordpress_1     | PHP version:	7.3.27
wordpress_1     | php.ini used:	/etc/php7/php.ini
wordpress_1     | WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
wordpress_1     | WP-CLI vendor dir:	phar://wp-cli.phar/vendor
wordpress_1     | WP_CLI phar path:	/data
wordpress_1     | WP-CLI packages dir:	
wordpress_1     | WP-CLI global config:	
wordpress_1     | WP-CLI project config:	
wordpress_1     | WP-CLI version:	2.4.0

```

I hope this is clear and posted at the right place.

**Comment by esteban1983cl** [comment]
I have this issue when use wp core core multisite-install command. The variable value`define( 'DOMAIN_CURRENT_SITE', 'blogs.localhostdata' );` is set to `define( 'DOMAIN_CURRENT_SITE', '127.0.0.1' );`

I think that the issue is because this block in wp-config.php
```php
if (defined('WP_CLI')) {
    $_SERVER['HTTP_HOST'] = '127.0.0.1'
}
```

Somebody know how solve this issue ?

**Comment by Rahe** [comment]
Hello,

I've tried your method on a blank WordPress installation and the "data" is not added to my configuration file or in the database.

Nicolas,

**Comment by n-goncalves** [comment]
My bad, I missed your comment. 

I can confirm this no longer happens when using WP-CLI 2.8.1. I'll close this since then, thanks.
