### ISSUE TITLE
wp core update fails and succeeds randomly

### ISSUE THREAD

**Issue by Starlette** [wp-cli/core-command#180]
Hi, I manage multiple Wordpress sites and run the same `wp core update` query on all of them. Some succeed and some fail. 

Here are the messages I get from the ones that failed. 
You'll notice that they are all updating to version 5.6.1 but all the urls are different.

```
Updating to version 5.6.1 (en_US)...
Downloading update from http://downloads.wordpress.org/release/wordpress-5.6.1-new-bundled.zip...
Error: Download failed.
ERROR: Job failed: exit code 1

Updating to version 5.6.1 (en_US)...
Downloading update from https://downloads.wordpress.org/release/wordpress-5.6.1-no-content.zip...
Error: Download failed.
ERROR: Job failed: exit code 1

Updating to version 5.6.1 (en_GB)...
Downloading update from http://downloads.wordpress.org/release/en_GB/wordpress-5.6.1.zip...
Error: Download failed.
ERROR: Job failed: exit code 1

Updating to version 5.6.1 (en_US)...
Downloading update from https://downloads.wordpress.org/release/wordpress-5.6.1-no-content.zip...
Error: Download failed.
ERROR: Job failed: exit code 1
```

Here are examples of the ones that succeeded.

```
Updating to version 5.6.1 (en_US)...
Downloading update from https://downloads.wordpress.org/release/wordpress-5.6.1-no-content.zip...
Unpacking the update...
Success: WordPress updated successfully.

Updating to version 5.6.1 (en_ZA)...
Downloading update from https://downloads.wordpress.org/release/en_ZA/wordpress-5.6.1.zip...
Unpacking the update...
Cleaning up files...
No files found that need cleaning up.
Success: WordPress updated successfully.
```

What could be causing the downloads to fail? I can't see a pattern.

**Comment by wojsmol** [comment]
Hi
Did yo have in logs source WordPress versions for failing websites?

**Comment by Starlette** [comment]
> 
> 
> Hi
> Did yo have in logs source WordPress versions for failing websites?

None sorry but I suspect it could be that the SSL verification is picking up an issue with WordPress' SSL certificates. The security implemented on this server is strict and won't allow downloads from sites that are not secure.

What I'm doing now (workaround to get it updated) is setting it up on my localhost (also blocked for updating from the admin panel - security is strict) then adding a Wordpress filter to disable SSL verification. With that enabled I can run the updates on my local using the admin panel then push the updated files to the server (with the filter I just added removed - not allowed to keep that in).
