### ISSUE TITLE
Download fails only with pt_BR locale

### ISSUE THREAD

**Issue by danielkza** [wp-cli/core-command#19]
```bash
# /usr/local/bin/wp core download --locale=pt_BR --version=4.8 --debug
Debug (bootstrap): No readable global config found (0.048s)
Debug (bootstrap): No project config found (0.048s)
Debug (bootstrap): ABSPATH defined: /var/www/wordpress/ (0.049s)
Debug (bootstrap): Running command: core download (0.049s)
Downloading WordPress 4.8 (pt_BR)...
md5 hash verified: bb0a041d922986f4d730ba176f89cd3e
Error: Couldn't extract WordPress archive. unable to decompress gzipped phar archive "/tmp/wp_595d37a3dad49.tar.gz" to temporary file
```

The same issue does not seem to happen with the en_US or es_ES locales (haven't had the time to test others).

Manually inspecting and extracting the archive with `tar` does not indicate there is any issue with it. All the files seem intact.

**Comment by danielbachhuber** [comment]
Hi @danielkza,

Thanks for the report. I can't seem to reproduce the bug:

```
$ wp core download --locale=pt_BR --version=4.8 --debug
Debug (bootstrap): Required file from config: /Users/danielbachhuber/.wp-cli/pre-ssh.php (0.011s)
Debug (bootstrap): Loading packages from: /Users/danielbachhuber/wp-cli/packages/vendor/autoload.php (0.011s)
Debug (bootstrap): Using default global config: /Users/danielbachhuber/.wp-cli/config.yml (0.08s)
Debug (bootstrap): No project config found (0.08s)
Debug (bootstrap): argv: /Users/danielbachhuber/wp-cli/bin/../php/boot-fs.php core download --locale=pt_BR --version=4.8 --debug (0.08s)
Debug (bootstrap): ABSPATH defined: /Users/danielbachhuber/projects/test/ (0.08s)
Debug (bootstrap): Running command: core download (0.081s)
Downloading WordPress 4.8 (pt_BR)...
md5 hash verified: bb0a041d922986f4d730ba176f89cd3e
Success: WordPress downloaded.
```

Can you reproduce on a different system, to verify the issue is specific to WP-CLI and not environmental?

**Comment by danielkza** [comment]
I can reproduce it in a clean Ubuntu 16.04 Docker container:

```dockerfile
FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates php-cli
RUN curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /usr/local/bin/wp && chmod +x /usr/local/bin/wp
RUN useradd -m www

USER www
RUN mkdir -p ~/wp-en_US && cd ~/wp-en_US && wp core download --version=4.8 --locale=en_US
RUN mkdir -p ~/wp-pt_BR && cd ~/wp-pt_BR && wp core download --version=4.8 --locale=pt_BR
```

**Comment by danielbachhuber** [comment]
Ok. This seems like a problem specific to your environment (PHP configuration or otherwise), not a bug with WP-CLI.

**Comment by danielkza** [comment]
Were you not able to reproduce it with the dockerfile? It contains no
custom configuration whatsoever. I was able to observe at home the same
problem I originally observed in AWS. How did you rule out a WP CLI issue?

Em sex, 7 de jul de 2017 09:40, Daniel Bachhuber <notifications@github.com>
escreveu:

**Comment by danielbachhuber** [comment]
> How did you rule out a WP CLI issue?

If I can't reproduce it locally with the steps provided, then it doesn't reproduce between environments and isn't a logical bug.

We don't provide support for arbitrary environments.

If you [google the error message](https://www.google.com/search?q=unable+to+decompress+gzipped+phar+archive&oq=unable+to+decompress+gzipped+phar+archive&aqs=chrome..69i57j0.515j0j7&sourceid=chrome&ie=UTF-8), it appears there are a couple of possibilities:

* [/tmp directory might not be writable](https://stackoverflow.com/a/42095311/6800777)
* You're missing a system utility or PHP extension inside of the environment.

**Comment by danielkza** [comment]
That would not explain why one locale works and another does not. All of
them would fail if any prerequisites were missing.

Em sex, 7 de jul de 2017 09:52, Daniel Bachhuber <notifications@github.com>
escreveu:
