### ISSUE TITLE
[PHP 8.1] `wp core install` fails with "Table wp_options doesn't exist" error

### ISSUE THREAD

**Issue by phillip-elm** [wp-cli/core-command#198]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

`wpcli core install` fails to install when using PHP 8.1, but works in PHP 7.4 and PHP 8.0 with the exact same setup.

```
Fatal error: Uncaught mysqli_sql_exception: Table 'local_test.wp_options' doesn't exist in /var/www/html/wp-includes/wp-db.php:2056
Stack trace:
#0 /var/www/html/wp-includes/wp-db.php(2056): mysqli_query()
#1 /var/www/html/wp-includes/wp-db.php(1945): wpdb->_do_query()
#2 /var/www/html/wp-includes/wp-db.php(2581): wpdb->query()
#3 /var/www/html/wp-includes/functions.php(1734): wpdb->get_var()
#4 /var/www/html/wp-includes/load.php(752): is_blog_installed()
#5 /var/www/html/wp-settings.php(159): wp_not_installed()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1271): require('...')
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1192): WP_CLI\Runner->load_wordpress()
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(77): WP_CLI\Bootstrap\LaunchRunner->process()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#11 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#12 /usr/local/bin/wp(4): include('...')
#13 {main}
  thrown in /var/www/html/wp-includes/wp-db.php on line 2056
```

**Describe how other contributors can replicate this bug**

- Create a clean install of Ubuntu 20.04 (or use the equivalent Docker `wordpress:cli-php8.1` flow)
- Install MariaDB, and PHP 8.1
- Run `wp core download`
- Run `wp config create` (I verified the output was correct)
- Run:

```bash
wp core install --title=Test --url="https://dev.foo.com" --admin_user=admin --admin_email=admin@foo.com --admin_password=foobar --skip-email
```

**Describe what you would expect as the correct outcome**

The command should create the needed database tables and should not fail in this way.

**Let us know what environment you are running this on**

```
OS:     Linux 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.1
PHP version:    8.1.0
php.ini used:   /etc/php/8.1/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.3.32-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/html
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.5.0
```

**Comment by sitamet** [comment]
confirmed. Same error.

**Comment by rotecodefraktion** [comment]
Same here 
php 8.1
debian 11
OS:	Linux 5.10.0-10-arm64 #1 SMP Debian 5.10.84-1 (2021-12-08) aarch64
Shell:	/bin/bash
PHP binary:	/usr/bin/php8.1
PHP version:	8.1.1
php.ini used:	/etc/php/8.1/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (aarch64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/html/wordpress
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.5.0

**Comment by rotecodefraktion** [comment]
I tried to install WP 5.8.2 from tarball and it runs with php 8.1.1 into a connection error to database because the values from install/setup page were not correctly parsed.  This cause that no tables where created and the following steps fails.
Download the 5.9 Beta / RC fix that problem.

`wp core download --version==5.9-RC2 `

**Comment by ocean90** [comment]
> Download the 5.9 Beta / RC fix that problem.

This issue was fixed in WordPress itself, see https://core.trac.wordpress.org/ticket/52825.

**Comment by phillip-elm** [comment]
@ocean90 ah - thanks for the link. will close this for now then.
