### ISSUE TITLE
Unless --path ends in a slash it won't detect that WP is already present.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/core-command#20]
For instance
```
WP_CLI_STRICT_ARGS_MODE=1 wp core download --path=/var/www/gosh
```
will download repeatedly.

(Is having to specify `WP_CLI_STRICT_ARGS_MODE` the only way to get `--path` recognized?)

I've a PR with this fix plus some miscellaneous test fixes incoming...

**Comment by danielbachhuber** [comment]
> (Is having to specify `WP_CLI_STRICT_ARGS_MODE` the only way to get --path recognized?)

No, `--path=<path>` is recognized without `WP_CLI_STRICT_ARGS_MODE`
