### ISSUE TITLE
Support `--no-extract` in `wp core download`

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/core-command#202]
## Feature Request

 

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Feature request [from Slack](https://wordpress.slack.com/archives/C02RP4T41/p1646921699739609):

> Hey, is it possible to download the WordPress archive with wp-cli command and extract it with another command?
>
> Use case : I need to cache wp archives, but I need to install with the user permissions. (Cache only works with root permissions), because we need to share archives between all server users. Any advices?

**Describe the solution you'd like**

Adding an `--extract` argument that defaults to `true` and can be opted out from using `--no-extract`.

If opted out, WP-CLI would just download the archive to the target location but not extract it.

**Comment by xyulex** [comment]
I wouldn't mind checking out this one!
