### ISSUE TITLE
Command wp core download <download-url> not working

### ISSUE THREAD

**Issue by John-Henrique** [wp-cli/core-command#209]
`wp core download <download-url>` not working with custom URLs... every time result in fail. The docs have [an example](https://developer.wordpress.org/cli/commands/core/download/), but works only with oficial download.

`wp core download https://site.com/wp-custom.zip  --path=/home/eczjyighsl/htdocs/8290346751.site.com `

This way, I can download but get WordPress latest version (not my wp-custom.zip).
`wp core download  --path=/home/eczjyighsl/htdocs/8290346751.site.com --url=https://site.com/wp-custom.zip ` 

Never get my custom from URL.

Ubuntu 22.04
Nginx

Any idea?

**Comment by danielbachhuber** [comment]
Thanks for the report, @John-Henrique !

> `wp core download <download-url>` not working with custom URLs... every time result in fail.

What error do you see? Can you share steps I can use to reproduce the issue?

**Comment by John-Henrique** [comment]
@danielbachhuber 

Steps to reproduce

Put a custom of WordPress zip online (I put in root of my domain), so I can access by https://site.com/wp-custom.zip

run command `wp core download https://site.com/wp-custom.zip` 

No errors are displayied, but I get download 'wordpress-6.0.2.zip' from  WordPress.org instead my wp-custom.zip

**Comment by danielbachhuber** [comment]
> Put a custom of WordPress zip online (I put in root of my domain), so I can access by https://site.com/wp-custom.zip

@John-Henrique Maybe the problem is with your custom ZIP? How are you creating it?

Using a WordPress core ZIP seems to work fine:

```
$ wp core download https://downloads.wordpress.org/release/wordpress-4.5.2.zip
Downloading from https://downloads.wordpress.org/release/wordpress-4.5.2.zip ...
md5 hash verified: e93d94d9cde6b6d75779e7f7ef72f428
Success: WordPress downloaded.
$ ls
index.php            wp-activate.php      wp-comments-post.php wp-cron.php          wp-load.php          wp-settings.php      xmlrpc.php
license.txt          wp-admin             wp-config-sample.php wp-includes          wp-login.php         wp-signup.php
readme.html          wp-blog-header.php   wp-content           wp-links-opml.php    wp-mail.php          wp-trackback.php
```
