### ISSUE TITLE
wp core download --skip-content removes themes/plugins directories outside wp-content

### ISSUE THREAD

**Issue by cathal-maverick** [wp-cli/core-command#214]
## Bug Report

**Describe the current, buggy behavior**

After running `wp core download --skip-content` the tinymce editor is broken due to missing plugins & themes directories

**Describe how other contributors can replicate this bug**

- run `wp-core download --skip-content`
- attempt to edit content using the TinyMCE editor
- the editor is unresponsive & console shows a 404 for js files
- inspecting the `wp-includes/js/tinymce` directory shows the plugins & themes directories are both missing

**Describe what you would expect as the correct outcome**

`wp core download --skip-content` should only remove the plugins & themes directories in the wp-content directory

**Let us know what environment you are running this on**

```
WP-CLI version:	2.7.0
```

**Provide a possible solution**

Add an additional check to only remove plugins & themes from the wp-content directory
https://github.com/wp-cli/core-command/blob/ac58bb1f5dd25969537d93c32f6afa7f3fd45ec3/src/Core_Command.php#L1527-L1529

**Provide additional context/Screenshots**

<img width="1248" alt="MicrosoftTeams-image (11)" src="https://user-images.githubusercontent.com/32732059/195844977-c4f9ba03-05a2-45d8-96da-8234530a0627.png">

Bug appears to have been introduced in #212

**Comment by danielbachhuber** [comment]
Thanks for the report, @cathal-maverick !

This is an annoying bug 😦 Fortunately, it seems there's a simple fix: #215

We'll likely release WP-CLI v2.7.1 in the near future to address.

**Comment by schlessera** [comment]
This fix was pushed as a patch release with [release v2.7.1](https://make.wordpress.org/cli/2022/10/18/wp-cli-v2-7-1-release-notes/).
