### ISSUE TITLE
Format --format in core version

### ISSUE THREAD

**Issue by gemal** [wp-cli/core-command#245]
If I try to run `wp core version --format=json`
I get:
```
Error: Parameter errors:
 unknown --format parameter
```

**Comment by swissspidy** [comment]
Thanks for your suggestion!

What would be your expected output for this case and what would it be useful for?

Maybe something like this?

```
$ wp core version --format=json
{ "version": "6.4.1" }
```

**Comment by gemal** [comment]
Yes that would be perfect!

**Comment by swissspidy** [comment]
While it probably wouldn't be difficult to get the same output with `wp core version` + `jq`, I suppose we could add this.

Would you be interested in attempting to submit a pull request as part of [today's WP-CLI Hack Day](https://make.wordpress.org/cli/2023/10/18/save-the-date-wp-cli-hack-day-on-friday-november-10th/)?

**Comment by danielbachhuber** [comment]
@gemal Out of curiosity, why is a string insufficient?

**Comment by gemal** [comment]
I just have a tool that scans through a lot of wordpress sites and extracts various information about them like plugins, themes, users and I needed to also show the version and all of the other commands supported returning json so I build my tool that way so I just found it strangely inconsistent that core version did not support this

**Comment by ernilambar** [comment]
Output of `wp core version` is always a single value and it is obviously a version. So adding format option for the output with single value seems extraneous to me also. 

`jq` could be piped if formatted JSON value is needed. 

**Example:**

```bash
wp core version | jq -R -c '{version:.}'
```
