### ISSUE TITLE
[ wp core check-update  ] - format options parameter

### ISSUE THREAD

**Issue by riccardodicurti** [wp-cli/core-command#250]
Summary:
From the information contained in the WordPress Developer Resources I read that it can set the return format https://developer.wordpress.org/cli/commands/core/update/ but give a return only for table format.

Steps to reproduce:
Run command ‘wp core check-update --format=json’

`	/**
	 * Checks for WordPress updates via Version Check API.
	 *
	 * Lists the most recent versions when there are updates available,
	 * or success message when up to date.
	 *
	 * ## OPTIONS
	 *
	 * [--minor]
	 * : Compare only the first two parts of the version number.
	 *
	 * [--major]
	 * : Compare only the first part of the version number.
	 *
	 * [--force-check]
	 * : Bypass the transient cache and force a fresh update check.
	 *
	 * [--field=<field>]
	 * : Prints the value of a single field for each update.
	 *
	 * [--fields=<fields>]
	 * : Limit the output to specific object fields. Defaults to version,update_type,package_url.
	 *
	 * [--format=<format>]
	 * : Render output in a particular format.
	 * ---
	 * default: table
	 * options:
	 *   - table
	 *   - csv
	 *   - count
	 *   - json
	 *   - yaml
	 * ---
	 *
	 * ## EXAMPLES
	 *
	 *     $ wp core check-update
	 *     +---------+-------------+-------------------------------------------------------------+
	 *     | version | update_type | package_url                                                 |
	 *     +---------+-------------+-------------------------------------------------------------+
	 *     | 4.5.2   | major       | https://downloads.wordpress.org/release/wordpress-4.5.2.zip |
	 *     +---------+-------------+-------------------------------------------------------------+
	 *
	 * @subcommand check-update
	 */
	public function check_update( $_, $assoc_args ) {

		$updates = $this->get_updates( $assoc_args );
		if ( $updates ) {
			$updates   = array_reverse( $updates );
			$formatter = new Formatter(
				$assoc_args,
				[ 'version', 'update_type', 'package_url' ]
			);
			$formatter->display_items( $updates );
		} elseif ( empty( $assoc_args['format'] ) || 'table' === $assoc_args['format'] ) {
			WP_CLI::success( 'WordPress is at the latest version.' );
		}
	}
`

**Comment by danielbachhuber** [comment]
Thanks for the report, @riccardodicurti 

I believe `wp core check-update --format=json` returns an empty result because there are no updates available.

What is your expected behavior?

**Comment by riccardodicurti** [comment]
Ciao @danielbachhuber
I would at least expect an empty json or a message telling me that no updates are available.

**Comment by danielbachhuber** [comment]
> I would at least expect an empty json or a message telling me that no updates are available.

I'm not sure a message would make sense. If you're passing the data into JSON parser, a string would break the parser.

`wp post list --format=json` produces an empty array:

```
$ wp post list --format=json
[]
```

Would an empty array work for your purposes?

Also, for posterity, could you share a bit more detail about your use case?

**Comment by riccardodicurti** [comment]
Yes, my suggestion was definitely to return the message via json. In any case, the empty array is still sufficient to verify that we have received the response.

I am currently writing a set of tests and update routines via ssh using the cli.

**Comment by danielbachhuber** [comment]
Ok, makes sense. I think I'd be fine to change `wp core check-update --format=json` to return an empty array, and consider this a bug in the original implementation.
