### ISSUE TITLE
Example of core update command

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/core-command#252]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

`wp core update` has following example:

```
# Update WordPress to latest version of 3.8 release
$ wp core update --version=3.8 ../latest.zip
```

When zip file is given, `--version` seems to be extraneous here I guess.

**Comment by danielbachhuber** [comment]
Yeah, we can remove it from the example.
