### ISSUE TITLE
Error: The requested locale (uk) was not found.

### ISSUE THREAD

**Issue by oleg-valko-pro** [wp-cli/core-command#263]
Summary:
I'm getting an error when loading the core in Ukrainian.

Steps to reproduce:
1. Run command "wp core download --locale=uk"
2. Receive an error "Error: The requested locale (uk) was not found."

Additional information:
PHP binary:     /opt/homebrew/Cellar/php/8.2.12_1/bin/php
PHP version:    8.2.12
php.ini used:   /opt/homebrew/etc/php/8.2/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /Users/user/valet/n7
WP-CLI packages dir:    
WP-CLI cache dir:       /Users/user/.wp-cli/cache
WP-CLI global config:   
WP-CLI project config:  
WP-CLI version: 2.9.0

**Comment by ernilambar** [comment]
Ukrainian language does not seem to be released for WordPress version 6.5. Reference - https://make.wordpress.org/polyglots/teams/
