### ISSUE TITLE
Since a few days: PHP Fatal error

### ISSUE THREAD

**Issue by MoBlockbuster** [wp-cli/core-command#267]
Hi all,

I have been recognized for few days, that the wp core command throw an error.

If i run this command:

wpcli --path=$WORDPRESS_PATH core check-update --minor --format=count

I get this message:

#################################

PHP Fatal error:  Uncaught TypeError: array_reverse(): Argument #1 ($array) must be of type array, bool given in phar:///usr/local/bin/wpcli/vendor/wp-cli/core-command/src/Core_Command.php:85
Stack trace:
#0 phar:///usr/local/bin/wpcli/vendor/wp-cli/core-command/src/Core_Command.php(85): array_reverse(false)
#1 [internal function]: Core_Command->check_update(Array, Array)
#2 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#4 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(497): call_user_func(Object(Closure), Array, Array)
#5 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(441): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#6 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(464): WP_CLI\Runner->run_command(Array, Array)
#7 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1296): WP_CLI\Runner->run_command_and_exit()
#8 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#9 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#10 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#11 phar:///usr/local/bin/wpcli/php/boot-phar.php(20): include('phar:///usr/loc...')
#12 /usr/local/bin/wpcli(4): include('phar:///usr/loc...')
#13 {main}
  thrown in phar:///usr/local/bin/wpcli/vendor/wp-cli/core-command/src/Core_Command.php on line 85
Fatal error: Uncaught TypeError: array_reverse(): Argument #1 ($array) must be of type array, bool given in phar:///usr/local/bin/wpcli/vendor/wp-cli/core-command/src/Core_Command.php:85
Stack trace:
#0 phar:///usr/local/bin/wpcli/vendor/wp-cli/core-command/src/Core_Command.php(85): array_reverse(false)
#1 [internal function]: Core_Command->check_update(Array, Array)
#2 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#4 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(497): call_user_func(Object(Closure), Array, Array)
#5 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(441): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#6 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(464): WP_CLI\Runner->run_command(Array, Array)
#7 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1296): WP_CLI\Runner->run_command_and_exit()
#8 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#9 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#10 phar:///usr/local/bin/wpcli/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#11 phar:///usr/local/bin/wpcli/php/boot-phar.php(20): include('phar:///usr/loc...')
#12 /usr/local/bin/wpcli(4): include('phar:///usr/loc...')
#13 {main}
  thrown in phar:///usr/local/bin/wpcli/vendor/wp-cli/core-command/src/Core_Command.php on line 85

#################################

I am using the PHP version 8.2.22.

I am using the current version of wpcli: WP-CLI 2.11.0

Let me know if you need forther information.

Best regards

**Comment by ernilambar** [comment]
```
$updates = $this->get_updates( $assoc_args );

if ( $updates || 'table' !== $format ) {
	$updates   = array_reverse( $updates );

```

Here we are running `array_reverse` without being absolutely sure that $updates variable is array. `get_updates()` method seems to have possibility to return `false` also.

**Comment by MoBlockbuster** [comment]
Hi all,

any news here?

Cheers

**Comment by ernilambar** [comment]
We are open to a pull request here! Feel free to submit one, if you'd like. Here is some guidance on [our pull request best practices](https://make.wordpress.org/cli/handbook/contributions/pull-requests/).
