### ISSUE TITLE
Improve support for .htaccess when installing or converting to Multisite

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/core-command#27]
When a site is converted to Multisite with `wp core multisite-convert`, or when Multisite is installed with `wp core multisite-install`, the relevant Multisite constants are added to `wp-config.php`, but nothing is added to `.htaccess` if the server is running on Apache.

Similarly, both of these commands provide an informational message saying "Don't forget to set up rewrite rules", but nothing about `.htaccess` is mentioned.

WP-CLI could either attempt to write to `.htaccess` itself, using the same rules that core generates after installing Multisite from the Tools -> Network Setup screen, or it could simply add an extra informational message about `.htaccess`.

**Comment by johnbillion** [comment]
I guess a link to the Nginx page on the Codex would help too, when Nginx is in use.

**Comment by danielbachhuber** [comment]
> WP-CLI could either attempt to write to `.htaccess` itself, using the same rules that core generates after installing Multisite from the Tools -> Network Setup screen, or it could simply add an extra informational message about `.htaccess`.

The latter seems most appropriate to me, if WordPress' behavior is to display the rules but not attempt to add them.
