### ISSUE TITLE
Adding a no-cache option to avoid using cached items

### ISSUE THREAD

**Issue by b4dnewz** [wp-cli/core-command#30]
I would like to suggest to introduce a `--no-cache` (or similar) option to explicitly avoid to use the cached zip files when performing `wp core download`. wp-cli/wp-cli#4308

It could be useful in different scenarios and probably not to complicated to implement (I guess).

**Comment by danielbachhuber** [comment]
> It could be useful in different scenarios

Could you explain how it would be useful in these different scenarios?

**Comment by gitlost** [comment]
I was thinking it could be useful in low disk space situations, where it means both "don't check the cache" and "don't save to cache".

**Comment by danielbachhuber** [comment]
> it means both "don't check the cache" and "don't save to cache".

This is already possible: `export WP_CLI_CACHE_DIR=/dev/null`

**Comment by gitlost** [comment]
Ah, very good.
