### ISSUE TITLE
wp core update doesn't release lock if download times out

### ISSUE THREAD

**Issue by windyjonas** [wp-cli/core-command#35]
It seems like the core_updater.lock option isn't removed if we get a timeout from downloads.wordpress.org.
```
$ wp core update
Updating to version 4.8.2 (en_US)...
Laddar ner uppdatering från https://downloads.wordpress.org/release/wordpress-4.8.2-no-content.zip...
Warning: cURL error 28: Connection timed out after 10000 milliseconds
Error: cURL error 28: Connection timed out after 10000 milliseconds
$ wp core update
Updating to version 4.8.2 (en_US)...
Error: En annan uppdatering körs för närvarande.
$ wp option delete core_updater.lock
```
(The error message is in Swedish and says: Error: Another update is currently in progress )

See also:
https://core.trac.wordpress.org/ticket/41954

**Comment by danielbachhuber** [comment]
Thanks @windyjonas, we'll get this fixed.

**Comment by danielbachhuber** [comment]
This is actually a bit more tricky than I expected.

The `WP_CLI::error()` call is within `WP_CLI\Utils\http_request()`, which is called from our subclass of `download_package()`:

* https://github.com/wp-cli/core-command/blob/v1.0.2/src/WP_CLI/CoreUpgrader.php#L76
* https://github.com/wp-cli/wp-cli/blob/v1.3.0/php/utils.php#L589

@wp-cli/committers Any opinions on a fix? Some options:

1. Internalize `WP_CLI\Utils\http_request()` to `WP_CLI\CoreUpgrader`.
    * Pro: we have greater control over the exception logic.
    * Con: duplicate code.
2. Add some flag to `WP_CLI\Utils\http_request()` that overrides the `WP_CLI::error()` behavior (instead passing the error back up).
    * Pro: reduces duplicate code.
    * Con: `wp-cli/core-command` is now dependent on a newer version of WP-CLI and we have to figure out how to do dependencies.
3. Avoid subclassing with `WP_CLI\CoreUpgrader` entirely and see if we can leverage the `upgrader_pre_download` filter. I think the subclass happened back when we supported WP 3.5.
    * Pro: Removes duplicative code path.
    * Con: I'm not 100% sure this is possible. Furthermore, there were some nasty historical bugs around this code path (that were fixed) and I'm not keen to accidentally introduce more.

What options am I missing?

**Comment by schlessera** [comment]
With 2., we can make use of the `$options` argument to `http_request()`. Add a check at the end to see whether `forward_exception` or something has been set to true, and then juts forward the exception instead of calling `WP_CLI::error()`.

The con is not relevant here, as the worst case is that the options is not set (and would default to false), and then it will just produce the same behaviour as now.

**Comment by danielbachhuber** [comment]
> With 2., we can make use of the `$options` argument to `http_request()`.

Oh, great idea. Doing so.
