### ISSUE TITLE
Avoid needing to update tests for every WordPress release

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/core-command#4]
Instead of #3 and https://github.com/wp-cli/wp-cli/pull/3880, we should come up with some reliable abstraction that means we don't have to update tests fro every WordPress release.

**Comment by schlessera** [comment]
We can directly use `api.wordpress.org` to fetch the latest version and store it. Then compare against this version. The API should provide both the version and the link to download.

**Comment by gitlost** [comment]
I tried out a more hacky scheme that scrapes https://wordpress.org/download/release-archive/ to get the latest subversions of all versions and puts them in an array that can be accessed by special {WP_VERS[ver]} variables - see https://github.com/gitlost/core-command/pull/2.

**Comment by danielbachhuber** [comment]
@gitlost Why not use `api.wordpress.org` to access all versions?

**Comment by gitlost** [comment]
Yes that's the best way. (I thought I'd need the previous versions too and didn't want to have to do the version decrement maths - but it turned out they're not needed. Also it was quite handy to deal with the preg arrays!)

**Comment by gitlost** [comment]
What do you think of the "{WP_VERS[ver]}" scheme - is it worth pursuing?

**Comment by danielbachhuber** [comment]
> What do you think of the "{WP_VERS[ver]}" scheme - is it worth pursuing?

It's confusing and I don't quite understand it. I think it'd be better to go with something simpler.

**Comment by gitlost** [comment]
The latest iteration of https://github.com/gitlost/core-command/pull/2 uses `api.wordpress.org`, and the variable syntax has been decryptified to `{WP_VERSION-version-latest}` - alternative suggestions welcome.

(I also did a demo `wp core latest_version` command https://github.com/gitlost/core-command/pull/4, which might be useful in shell scripts.)

**Comment by danielbachhuber** [comment]
> The latest iteration of gitlost#2 uses api.wordpress.org, and the variable syntax has been decryptified to {WP_VERSION-version-latest} - alternative suggestions welcome.

This looks good. Can you submit the PR against this repo, and also against `wp-cli/wp-cli` ?
