### ISSUE TITLE
Skip caching when upgrading to nightly builds

### ISSUE THREAD

**Issue by westonruter** [wp-cli/core-command#43]
I just made a new build for the 4.9 branch and then I tried upgrading to it via WP-CLI, which I had used to upgrade to a nightly branch build previously. WP-CLI tried to use the previously-cached ZIP:

```
$ wp core upgrade --force http://wordpress.org/nightly-builds/wordpress-4.9-latest.zip
Starting update...
Using cached file '/root/.wp-cli/cache/core/wordpress-4.9-latest-.zip'...
Unpacking the update...
```

Obviously this is not what I wanted. So I had to add a cache-busting query parameter to force it to skip the cache.

I think that if the URL contains “nightly-builds” then the caching should be bypassed.

Related: #17

**Comment by danielbachhuber** [comment]
Why no secure?!

![image](https://user-images.githubusercontent.com/36432/32726936-a3deb3fc-c82f-11e7-9ef9-232bc0137f6a.png)

We can handle `http` too.
