### ISSUE TITLE
wp core download --locale=cs_CZ

### ISSUE THREAD

**Issue by vyskoczilova** [wp-cli/core-command#49]
I tried to download a wp core in Czech with a command `wp core download --locale=cs_CZ` but it tells me that `Error: The requested locale (cs_CZ)` was not found. How is that possible? Normally, from a repo I can download a Czech version. Thanks i advance

**Comment by danielbachhuber** [comment]
Hi @vyskoczilova,

`wp core download --locale=cs_CZ` requires the Czech locale to be built for WordPress 4.9, which it may not yet be. As an alternative, you may be able to `wp core download && wp language core install cs_CZ --activate`.

**Comment by vyskoczilova** [comment]
Ok, thanks a lot!
