### ISSUE TITLE
--skip-email doesn't skip sendmail invocation

### ISSUE THREAD

**Issue by strarsis** [wp-cli/core-command#50]
Albeit `--skip-email` option is used with `wp core install`, 
sendmail is still invoked, resulting in an error 
(because it hadn't been installed/configured on that system).

````
sh: 1: -t: not found
````
This is a [symptom](http://axiac.ro/blog/sh-1-t-not-found/) for invoking sendmail that hadn't been installed and/or configured yet.
So some code in WordPress is indeed still trying to invoke sendmail.

Code with instructions for reliably reproducing the issue: 
https://github.com/strarsis/wp-core-skip-email-demo
````
$ git clone https://github.com/strarsis/wp-core-skip-email-demo
$ cd wp-core-skip-email-demo
$ docker-compose up -d && ./setup.sh localhost 8080
````
The aforementioned error is logged during the first time setup.

**Comment by gitlost** [comment]
It might be the new "Notice of Admin Email Change" email https://core.trac.wordpress.org/ticket/39117, which was catered for in https://github.com/wp-cli/core-command/pull/45, so maybe if you could try the nightly and see if that fixes it for you...

**Comment by strarsis** [comment]
@gitlost: I modified the live demo code to use the nightly release of wp.

For doing the same in case you already cloned and tried out the repo:
````
(Inside the cloned repo)
$ git pull
$ docker-compose down
$ docker-compose build # rebuild the image
$ docker-compose up -d

# Check version of wp (that nightly is indeed installed):
$ docker-compose exec bash wordpress
# wp --allow-root --version
# exit

$ ./setup.sh localhost 8080
````
The message is still logged.

**Comment by gitlost** [comment]
If I change `Dockerfile-wordpress` to directly download the nightly `https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar`:
```
FROM wordpress

# wp cli
RUN apt-get update \
 && apt-get install --no-install-recommends -y \
      sudo less mariadb-client-core-10.0 \
 && apt-get clean \
 && curl -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar \
 && chmod +x /usr/local/bin/wp

```
then it appears to work... (Please note, I'm a total Docker n00b!)

**Comment by strarsis** [comment]
@gitlost: Thanks! 
So the `wp cli update --nightly` command doesn't seem to update to nightly.
A separate bug?

**Comment by gitlost** [comment]
Hmm, not sure, I'll familiarize myself with Docker (something I should have done yonks ago) and see if I can track the reason...

**Comment by gitlost** [comment]
Ah just need the `--yes` - `wp cli update --nightly --yes`!

**Comment by strarsis** [comment]
@gitlost: Thanks for your help. So with the next wp cli release this issue should be fixed then.

**Comment by gitlost** [comment]
Yes, probably in the new year...thanks for reporting!
