### ISSUE TITLE
--url optional

### ISSUE THREAD

**Issue by strarsis** [wp-cli/core-command#52]
`wp core install` requires `--url` parameter while 
the interactive WordPress setup doesn't ask for it or need it.

For some environments (e.g. docker), this can cause problems because 
the host and port have to be known – which can be even impossible in some cases.

Example invocation:
````
wp core install \
    --allow-root \
    --skip-email \
    --path=/var/www/html \
    --title="Example site" \
    --admin_user=admin \
    --admin_password="test" \
    --admin_email=info@example.com
````

**Comment by danielbachhuber** [comment]
> the interactive WordPress setup doesn't ask for it or need it.

Right — because `$_SERVER['HTTP_HOST']` is available. Some URL always needs to be specified during the installation process.

**Comment by strarsis** [comment]
@danielbachhuber: So can I somehow omit `--url` when `$_SERVER['HTTP_HOST']` is available to the CLI script? Or is this something that is only available when actually visiting the (setup page of) site using a browser?

**Comment by danielbachhuber** [comment]
`$_SERVER['HTTP_HOST']` is only present in web requests, so you'll always need to specify `--url=<url>` for CLI installation requests.

**Comment by strarsis** [comment]
@danielbachhuber: Thanks.
