### ISSUE TITLE
Make --skip-content flag available to more versions and locales

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/core-command#57]
In #37 and #40, we added `--skip-content` so that users could download WordPress without the default themes and plugins in `wp-content`. However, this is restricted to the `en_US` locale of the latest version.

In order to emulate `--skip-content` for other locales and versions, we could improve `WP_CLI\Extractor` to skip extraction of the `wp-content` directory from the archive file.

**Comment by danielbachhuber** [comment]
> we could improve `WP_CLI\Extractor` to skip extraction of the `wp-content` directory from the archive file.

Actually, there might be an easier way to do this: use `ZipArchive::deleteName()` to remove the `wp-content` directory from the ZIP archive.

**Comment by crstnio** [comment]
According to the documentation, this command should only exclude **plugins** and **themes** – not the entire `wp-content` directory.

By excluding the whole thing, you exclude the **languages** too and the `--locales=` option is broken.
