### ISSUE TITLE
Inconsistent (or missing) processing of --path on "core (multisite-)install"

### ISSUE THREAD

**Issue by jscheytt** [wp-cli/core-command#68]
Hello there,

when running "core install" together with `--path=...`, the base URL gets messed up.

Steps to reproduce:

1. Run `wp --path="~/public_html/example.com" core install --url="https://example.com" --title="example" --admin_email="x@example.com" --admin_user="x"` (or `core multisite-install`).
2. Open "https://example.com".
3. Observe errors: All resources (and sub-pages like /wp-admin/) are fetched/embedded from base URL "https://example.com/public_html/example.com".

This error does not happen when I `cd` into the site directory and perform step 1 without the `--path=...` parameter.

The "~/public_html/" in the example path above is specific to my install, but I suspect that the "/public_html/example.com" which is appended to the actual base URL is some kind of default value that is not being overwritten by the `core install` command.

**Comment by marksabbath** [comment]
Hey @jscheytt 

Have you found this issue in the latest version of wp-cli?

We are currently that same command on a bunch of installs and have never experienced that.

Would you mind providing the wp-cli version you're currently using?

**Comment by schlessera** [comment]
@jscheytt I don't think the `--path` argument understands the `~ => user home` expansion.

Can you try whether either using a full path or using `$HOME` works in your case:
```
wp --path="$HOME/public_html/example.com" core install --url="https://example.com" --title="example" --admin_email="x@example.com" --admin_user="x"
```

**Comment by jscheytt** [comment]
Sorry for missing details:

1. @marksabbath We are using the latest version of wp-cli.
1. @schlessera I wrote a path to be expanded for brevity, but I am in fact passing a full path from a variable like `--path="$full_path"`.

All other wp-cli commands I have worked with so far have no problems with the `--path` argument.

I just did some further testing. For clarity, here is the full (anonymized) command I tried for **core multisite-install**

```
wp --path="/usr/home/username/public_html/site_dir" core multisite-install --url="domain.com" --title=
"123" --admin_email="x@y.com" --admin_user="xy" --admin_password='' --subdomains --skip-email
```

and for **core install** respectively

```
wp --path="/usr/home/username/public_html/site_dir" core install --url="domain.com" --title="123" --admin_email="x@y.com" --admin_user="xy" --admin_password='' --skip-email
```

Either of these commands results in all URLs (e. g. asset URLs) being of the form `http://domain.com/public_html/site_dir/wp-includes/js/wp-embed.min.js?ver=4.9.6`. (Everything up to including 'site_dir/' seems to be the base URL.) This does not happen if I `cd` into 'site_dir' and perform the command without the `--path` argument.

**Comment by javorszky** [comment]
I could not reproduce this issue. I started with all WP files except for `wp-config.php`

```
13:46:59  ✘  javorszky@GaborrMBP  ~  ⬡ v10.6.0 
$ wpd config create --path=/Users/javorszky/Sites/wpcli-hackday/multisite --dbname=wpcli.multisite
Success: Generated 'wp-config.php' file.

 13:47:07  javorszky@GaborrMBP  ~  ⬡ v10.6.0 
$ wpd db drop --path=/Users/javorszky/Sites/wpcli-hackday/multisite
Are you sure you want to drop the 'wpcli.multisite' database? [y/n] y
Success: Database dropped.

 13:47:19  javorszky@GaborrMBP  ~  ⬡ v10.6.0 
$ wpd db create --path=/Users/javorszky/Sites/wpcli-hackday/multisite
Success: Database created.

 13:47:25  javorszky@GaborrMBP  ~  ⬡ v10.6.0 
$ redis-cli flushall
OK

 13:47:30  javorszky@GaborrMBP  ~  ⬡ v10.6.0 
$ wp core multisite-install --url=wpcms.test --title=foo --path=/Users/javorszky/Sites/wpcli-hackday/multisite
Created single site database tables.
Set up multisite database tables.
Added multisite constants to 'wp-config.php'.
Success: Network installed. Don't forget to set up rewrite rules (and a .htaccess file, if using Apache).

 13:47:45  javorszky@GaborrMBP  ~  ⬡ v10.6.0 
$
```

**Comment by jscheytt** [comment]
The server OS is Ubuntu, but I don't think this is part of the problem.

Instead I found following symbolic links in the path argument seems to generate problems:
* If I use a path like `/usr/home/username/public_html/sub.domain.com` where the first part (`/usr/home/username/public_html/`) is a symlink to e. g. `/usr/www/users/username/`, the problem stated at the top happens.
* If I instead use the actual hard path (`/usr/www/users/username/sub.domain.com`), the problem above does not appear.
