### ISSUE TITLE
Discrepancy between -is-installed and blog_is_installed()

### ISSUE THREAD

**Issue by berengerz-vortexsolution** [wp-cli/core-command#71]
Hi!

I have something strange on one of my websites (out of ~140, on which the command works fine), and cannot pinpoint the issue.

`wp core is-installed --allow-root && echo $?` returns `0` in my project, while a simple PHP file at the root with 

```
require_once 'wp-load.php';
var_dump(is_blog_installed());
```

called from CLI (`php test.php`) shows `bool(true)`

I read about the cache issues, but I cleared and deactivated WP Rocket on that project, with the same results.
Where could that inconsistence come from?

The websites runs perfectly, the other WP CLI commands work good too (wp option get siteurl returns the right value, wp option list returns them all, meaning that the DB is back there, wp theme list, etc.).

Any lead appreciated.

(can be a geeky comment/response, I'll handle).

**Comment by schlessera** [comment]
The shell exit code `0` actually means "success", so WP-CLI tells you that the site _is indeed installed_.

An exit code of `1` (or any non-zero value for that matter) denotes "failure" and would mean the site is not installed.
