### ISSUE TITLE
wp core install doesn't fully populate db

### ISSUE THREAD

**Issue by popindavibe** [wp-cli/core-command#82]
Hello,
I cannot get wp-cli to create the various pages  (about, contact) and menu I got when installing manually. Is that by design?
All I get generated are the post page and the privacy page [2]

The command is successful though, which I why I wonder if that is by design:
```
$ wp core install --url=https://example.com --title="My Blog" --admin_user="admin" --admin_password='XXXXXXXXXX' --admin_email="hostmaster@example.com"                                     
Success: WordPress installed successfully.
```

[2] From DB server:
```
$ mysql -ss -e "SELECT post_title,post_status,post_name,post_parent,post_type,menu_order from wp_example.com.wp_posts WHERE post_type = 'page'\G"
*************************** 1. row ***************************
 post_title: Privacy Policy
post_status: draft
  post_name: privacy-policy
post_parent: 0
  post_type: page
 menu_order: 0
*************************** 2. row ***************************
 post_title: Sample Page
post_status: publish
  post_name: sample-page
post_parent: 0
  post_type: page
 menu_order: 0
```

### What is your system?
lsb_release -a
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch
```

### Which version of PHP are you using?
```
$ which -a php
/usr/bin/php

$ php -v
PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
```

### Are you running suhosin? If so, make sure you've added `suhosin.executor.include.whitelist = phar` to your php.ini
php -m | grep -i suhosin
N/A

### Which version of WordPress are you using?
```
$ grep '^\$wp_version\s' wp-includes/version.php
$wp_version = '4.9.8';
```
### Can you share the results of which wp ?
which -a wp
```
/usr/local/bin/wp
```
stat $(which wp)
```
  File: /usr/local/bin/wp
  Size: 4577919         Blocks: 3457       IO Block: 131072 regular file
Device: 47h/71d Inode: 68176       Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-05-04 23:25:03.738614771 +0100
Modify: 2018-05-04 23:25:03.906614901 +0100
Change: 2018-05-04 23:25:03.910614904 +0100
 Birth: -
```
### Are you running any packages? If one is causing a problem, you can use `--skip-packages` to skip loading them
wp package list
```
+------+---------+---------+--------+----------------+
| name | authors | version | update | update_version |
+------+---------+---------+--------+----------------+
+------+---------+---------+--------+----------------+
```

**Comment by schlessera** [comment]
@popindavibe WordPress does not include an about page or a menu by default. You might have used a custom script to install WordPress, as they are provided by cPanel and similar.

The WordPress Core files generate:
1 "Hello World" post
1 comment on that post
1 "Sample Page" page
1 "Privacy Policy" page

**Comment by popindavibe** [comment]
Ooooh! Well I'm not 100% sure, but I think I initially just followed the '5 minutes install' on https://codex.wordpress.org/Installing_WordPress .

The strange thing is if I search for _Twenty Seventeen_ theme from the theme page and reload it, it then shows the menu with the 'Blog', 'Contact' and 'About' in it (though it did not download the photos, which is fine).
So not 100% sure why I get this half-installed theme through wp-cli at first, however if that is by design then so be it.
Thanks @schlessera for the quick reply, much appreciated.

**Comment by schlessera** [comment]
@popindavibe If I remember correctly, work was done on adding more default content to specific themes, but not sure about that.

Anyways, this is not a WP-CLI specific issue, so I'm closing here for now.
