### ISSUE TITLE
wp core install --url create wrong URL

### ISSUE THREAD

**Issue by Kuzdo** [wp-cli/core-command#9]
`wp core install --url` creates wrong URL.
I'm using WP-CLI on FreeBSD with no global installation. I have installed WP-CLI in home directory.
These are commands to reproduce:
```bash
[server]:<~/domains/domain.com/public_html>$ wp core install --url='http://www.domain.com/' --title=Example --admin_user=admin --admin_email=admin@email.com --skip-email
Admin password: ****
Success: WordPress installed successfully.
[server]:<~/domains/domain.com/public_html>$ wp option get home
http://www.domain.com/domains/domain.com/public_html
[server]:<~/domains/domain.com/public_html>$ wp option get siteurl
http://www.domain.com/domains/domain.com/public_html
[server]:<~/domains/domain.com/public_html>$
```

**Comment by danielbachhuber** [comment]
@Kuzdo Just to confirm, this is a fresh WordPress install with no mu-plugins, etc.?

Can you share the contents of your `wp-config.php`, minus any secrets?

Potentially related https://github.com/wp-cli/wp-cli/pull/2707
