### ISSUE TITLE
Temporarily switch to dev stability for `wp-cli/wp-cli`

### ISSUE THREAD

**Issue by schlessera** [wp-cli/core-command#91]
Current feature tests for `wp-cli/core-command` are broken because of an edge case in the way command namespaces are handled. This was fixed in `wp-cli/wp-cli` with https://github.com/wp-cli/wp-cli/issues/4950.

To get the tests to pass for now, we need to switch to the latest dev stability version of `wp-cli/wp-cli` until a new stable release of that package has been tagged. We only want to do that in tandem with `wp-cli/wp-cli-bundle`, though, to keep versions in sync between these two packages.

Once a new stable tag has been pushed for `wp-cli/wp-cli`, `wp-cli/core-command` should be moved back to require a stable version again.

**Comment by wojsmol** [comment]
This issue can be closed.
